apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: openstack
  source:
    repoURL: https://github.com/skyengpro/openstack-deployment.git
    targetRevision: feat/deploy-neutron-agent-on-bare-metal-using-containers
    path: charts/horizon-wrapper
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "jobs.db_init.enabled"
          value: "true"
        - name: "jobs.db_sync.enabled"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
